package ges.com.genesis.domain;
// Generated 16/01/2018 07:41:45 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name = "imagen")
public class Imagen implements java.io.Serializable {

	private int idimagen;
	private String nombre;
	private Integer idpost;
	private String url;
	private String dataImg;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Imagen() {
	}

	public Imagen(int idimagen) {
		this.idimagen = idimagen;
	}

	public Imagen(int idimagen, String nombre, Integer idpost, String url, String dataImg, Set<Usuario> usuarios) {
		this.idimagen = idimagen;
		this.nombre = nombre;
		this.idpost = idpost;
		this.url = url;
		this.dataImg = dataImg;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.IDENTITY)
	@Column(name = "idimagen", unique = true, nullable = false)
	public int getIdimagen() {
		return this.idimagen;
	}

	public void setIdimagen(int idimagen) {
		this.idimagen = idimagen;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "idpost")
	public Integer getIdpost() {
		return this.idpost;
	}

	public void setIdpost(Integer idpost) {
		this.idpost = idpost;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "data_img")
	public String getDataImg() {
		return this.dataImg;
	}

	public void setDataImg(String dataImg) {
		this.dataImg = dataImg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "imagen")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
